# Test utils_maths

## import module

In [3]:
%run ../config_jupyter.ipynb
%load_ext autoreload
%autoreload 2
%load_ext line_profiler

{'commit_hash': '523ed2fe5',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/home/luismiguel/.local/lib/python3.6/site-packages/IPython',
 'ipython_version': '7.2.0',
 'os_name': 'posix',
 'platform': 'Linux-4.15.0-45-generic-x86_64-with-Ubuntu-18.04-bionic',
 'sys_executable': '/usr/bin/python3',
 'sys_platform': 'linux',
 'sys_version': '3.6.7 (default, Oct 22 2018, 11:32:17) \n[GCC 8.2.0]'}
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
The line_profiler extension is already loaded. To reload it, use:
  %reload_ext line_profiler


/usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.24.1) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)


In [4]:
from diffractio import degrees, np
from diffractio.utils_math import *

## Distance

In [13]:
x1=np.array([0,1,1])
x2=np.array([0,0,1])

print(len(x1))

distance(x1,x2)

3


1.0

In [14]:
x1=np.array([0,0,0])
x2=np.array([1,1,1])

distance(x1,x2)

1.7320508075688772

In [17]:
x1=np.array([0,0,1j])
x2=np.array([0,0,1])

distance(x1,x2)

1.4142135623730951

## nearest y nearest2

In [32]:
x=np.linspace(0,10,21)

indexes, values, distances=nearest(x,5)
print(indexes, values, distances)

10 5.0 0.0


In [31]:
indexes, values, distances=nearest2(x,x)
print(indexes, values, distances)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ] [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [33]:
x=np.linspace(0,10,11)
indexes, values, distances=nearest2(x,x)
print(indexes, values, distances)

[ 0  1  2  3  4  5  6  7  8  9 10] [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## ndgrid 

In [40]:
x, y = [0, 1], [2, 3, 4]
X, Y = ndgrid(x, y)

print(X)

[[0 0 0]
 [1 1 1]]


## binarize

In [44]:
vector=np.linspace(0,1,6)
binarize(vector, min_value=0, max_value=1)

array([0., 0., 0., 1., 1., 1.])

In [45]:
vector=np.linspace(-1,1,6)
binarize(vector, min_value=-1, max_value=1)

array([-1., -1., -1.,  1.,  1.,  1.])

In [50]:
u=np.linspace(0,2*np.pi,6)
amplitude2phase(u)

np.exp(1j*u)

array([ 1.        +0.00000000e+00j,  0.30901699+9.51056516e-01j,
       -0.80901699+5.87785252e-01j, -0.80901699-5.87785252e-01j,
        0.30901699-9.51056516e-01j,  1.        -2.44929360e-16j])

## Normalize

In [52]:
v=np.array([1,1])
normalize(v,2)

array([0.70710678, 0.70710678])

In [54]:
v=np.array([1+1j,0])
normalize(v,2)

array([0.70710678+0.70710678j, 0.        +0.j        ])

## parms_to_list

### Jones 

In [11]:
params_to_list(J1, verbose=True)

(10.000000000000002, 0.7853981633974483, 3.141592653589793, 0.7853981633974483, 6.123233995736766e-17, 0.0, 3.1622776601683795)


(10.000000000000002,
 0.7853981633974483,
 3.141592653589793,
 0.7853981633974483,
 6.123233995736766e-17,
 0.0,
 3.1622776601683795)

### Jones_matrix

In [30]:
M1 = Jones_matrix('M1')


In [31]:
M1.diattenuator_linear(angle=45*degrees, p1=.9, p2=.1)

matrix([[0.5+0.j, 0.4+0.j],
        [0.4+0.j, 0.5+0.j]])

In [32]:
M1.Parameters:

Parameters: of M1 @45.00 deg:
    is_homogeneous: True
    delay:          0.000ª
    diattenuation:  0.976

In [33]:
params_to_list(M1, verbose=True)

(0.0, 0.975609756097561, True)


(0.0, 0.975609756097561, True)

### Stokes

In [38]:
S1 = Stokes('S1')
S1.general_carac_angles(
    alpha=22.5*degrees, delay=45*degrees, intensity=1, pol_degree=.5, is_dediffraction and interference=False)

matrix([[1.        ],
        [0.35355339],
        [0.25      ],
        [0.25      ]])

In [39]:
S1.Parameters:

Parameters: of S1:
    intensity             : 1.000 arb. u.
    amplitudes            : E0x 0.653, E0y 0.271, E0_unpol 0.707 
    degree diffraction and interference   : 0.500
    degree linear pol.    : 0.433
    degree   circular pol.: 0.250
    alpha                 : 22.500 deg
    delay                 : 45.000 deg
    azimuth               : 17.632 deg
    ellipticity  angle    : 15.000 deg
    ellipticity  param    : 0.268
    eccentricity          : 0.963
    polarized vector      : [+0.500; +0.354; +0.250; +0.250]'
    unpolarized vector    : [+0.500; +0.000; +0.000; +0.000]'

## Fast method

In [53]:
lista=[(k,v) for k,v in S1.Parameters:.dict_params.items()]

In [59]:
for l in lista:
    print("{}: {}".format(l[0],l[1]))

intensity: 1.0
amplitudes: (0.6532824824381883, 0.2705990500730985, 0.7071067811865476)
degree_pol: 0.5
degree_linear_pol: 0.43301270189221935
degree_circular_pol: 0.24999999999999994
alpha: 0.39269908169872414
delay: 0.7853981633974482
ellipticity_param: 0.26794919243112264
ellipticity_angle: 0.26179938779914935
azimuth: 0.30773985433519363
eccentricity: 0.9634330440022852
polarized: [0.5, 0.3535533905932738, 0.25, 0.24999999999999994]
unpolarized: [0.5, 0.0, 0.0, 0.0]
